### ISSUE TITLE
Stuck at "Building Terrain" - Build 1375 or newer! 

### ISSUE THREAD

**Issue by File14** [Nukkit/Nukkit#1108]
### Issue description
Commit that made it broke: https://github.com/Nukkit/Nukkit/commit/15e1b88e6e389ddf7453fa6ae6e90adc413c9b35
This is causing client hang on login on SOME old worlds. It gets stuck at "building terrain" but if you wait like 3 minutes you finally get into the server. See when it freezes: https://i.gyazo.com/dbfc5ada2f2c223650120495d50ef9b3.gif

### Steps to reproduce the issue
You can download the following world and test by yourself. Make sure to go to X: 0 Y: 100 and Z: 0
for the chunk to load. If you spawn in that position it will freeze at "building terrain" otherwise if you spawned in another place and go to the locaiton it will freeze your client. 

Download world: https://www.dropbox.com/s/6z761f16rf0vx35/world.zip?dl=1

### OS and versions

* Nukkit: Build 1375 - https://circleci.com/gh/Nukkit/Nukkit/1375
* OS: Host in on Linux but doesn't matter in this case.
* Device: Windows 10 but doesn't matter in this case.

### Crashdump, backtrace or other files
There are no sign of errors or bug reports.

**INFO**
This is @boy0001's commit so I suggest him to take a look at it.
@MrPowerGamerBR tested my world and is also having the same issuse with @boy0001's commit!

**Comment by MrPowerGamerBR** [comment]
I think https://github.com/Nukkit/Nukkit/commit/15e1b88e6e389ddf7453fa6ae6e90adc413c9b35 should be reverted temporarily while @boy0001 doesn't find the issue. However that's a shame, because some of the changes in the commit were amazing (maybe @boy0001 can commit parts of the commit in separate pull requests, example: The optimize movement in one commit, the optimize chunk in another, etc), that will be easier to find issues if it happens again.
