### ISSUE TITLE
Tall grass floats when block below it is broken

### ISSUE THREAD

**Issue by stayandwait** [Nukkit/Nukkit#1110]
### Issue description
Tall grass floats when you break the block that is beneath it.

### Steps to reproduce the issue
1. Look for naturally spawned tall grass.
2. Break the block beneath the tall grass.
3. The tall grass is now floating.

### OS and versions
* Nukkit: 468
* OS: Windows 10
* Device: PC

![2016-10-08_1647](https://cloud.githubusercontent.com/assets/15825041/19215844/003d66ec-8d77-11e6-8069-ff75cdc43243.png)

**Comment by MrPowerGamerBR** [comment]
Doesn't even need to be naturally spawned tall grass, any double flower, even the ones not naturally spawned causes this issue.

*Maybe* this happens due to my "let's remove double plant physics because it is causing too many issues!" commit.

**Comment by MrPowerGamerBR** [comment]
Yep https://github.com/ParappaTownMC/Nukkit/blob/6f24e723208f942a129b7d2ec73ef9e0522c88ac/src/main/java/cn/nukkit/block/BlockDoublePlant.java#L58

Okay, so it is because I removed the remove block check because it was causing dupe issues, fixing shouldn't be too hard, right? Just trigger a useBreakOn(getSide(Vector3.SIDE_UP));

**Comment by MrPowerGamerBR** [comment]
But, of course, using ```useBreakOn(getSide(Vector3.SIDE_UP));``` will be hacky, we need to do this:

1. When a double plant breaks, it triggers a block update to the near block
2. The top block of the plant gets the update and checks the state, the block below isn't a double plant so it drops the plant again

This causes a dupe issue where two flowers is dropped instead of one, we need to check if the block above or below is a double plant, if yes, then drop the flower item, if not, just break the flower block and do not drop anything.

**Comment by MrPowerGamerBR** [comment]
@stayandwait this is harder than I thought to fix, the update code for flowers is a mess and it is very difficult to fix it.
