### ISSUE TITLE
nukkit.io not work

### ISSUE THREAD

**Issue by tigerza117** [Nukkit/Nukkit#1144]
I've waited over 3 hours and I still haven't gotten my confirmation email. I've tried to make several accounts and resend the e-mail, which sucks 

because there's different plugins on nukkit.io and now I'm only able to use these.

**Comment by bonnedav** [comment]
Same. I tried to make an account a few weeks ago and I still haven't received the confirmation email.

From: tigerza117
Sent: Thursday, October 13, 7:56 AM
Subject: [Nukkit/Nukkit] nukkit.io not work (#1144)
To: Nukkit/Nukkit

I've waited over 3 hours and I still haven't gotten my confirmation email. I've tried to make several accounts and resend the e-mail, which sucks

because there's different plugins on nukkit.io and now I'm only able to use these.

-

**Comment by Snake1999** [comment]
Please do not use rude words

**Comment by SupremeMortal** [comment]
I tried with Google and my own domain but still not luck.

**Comment by AGTInformous** [comment]
Hm yes I tried to create a account 2 weeks ago and have the same problem

SupremeMortal <notifications@github.com> schrieb am Fr., 14. Okt. 2016,
19:14:

**Comment by MagicDroidX** [comment]
I've just looked into it.
Zoho, our mail provider, blocked our mail account due to mail rate limit.
Please try it again. :)

**Comment by bonnedav** [comment]
Ok it worked. Thank you.

**Comment by tigerza117** [comment]
And now I just got an email from nukkit.io .
This summary is also available. If this does not resolve the issue of the right to download it.
