### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by JackboyPlay** [Nukkit/Nukkit#1329]
It's more a question than an issues.
A few people said in an another issues that it is posibble to join to Nukkit with 1.0,
but I've tried to join to Nukkit over a proxy [Nemisys] and it says Outdated Server!
Is there an option to enable/disable Nukkit 1.0 support?

**Comment by daveboden** [comment]
My up-to-date Nukkit build reports this when connecting with Windows 10 MCPE v1.0.0 (which got upgraded overnight and I can't see any reasonable way of downgrading):

[INFO] [/127.0.0.1:19132] logged out due to Outdated server!

I've tried naively changing these lines to v1.0.0 in Nukkit.java :

`public final static String MINECRAFT_VERSION = "v0.16.0 alpha";`
`public final static String MINECRAFT_VERSION_NETWORK = "0.16.0";`

Unfortunately, it looks like the protocol has changed on the client side (probably the handshaking protocol which sets up the initial connection). I don't think anyone will be able to connect MCPE v1.0.0 to Nukkit or probably PocketMine servers until the protocol is determined and implemented on the servers side.

**Comment by kazuemon** [comment]
Protocol 100

**Comment by PikyCZ** [comment]
Why does nukkit team to update?

**Comment by EnderKenji** [comment]
when is it gonna be the update for Nukkit?

**Comment by boybook** [comment]
https://github.com/yescallop/Nukkit/tree/1.0

**Comment by EnderKenji** [comment]
Is it stable? When will merge to here?

**Comment by Pub4Game** [comment]
@yescallop Do you mind if I take your code? I'll create a separate thread and start Nukkit update to 1.0.0 and fix all future bugs.

**Comment by yescallop** [comment]
@Pub4Game Of course you can

**Comment by JackboyPlay** [comment]
@yescallop you made a really great job with updating Nukkit !

**Comment by File14** [comment]
@Pub4Game Close this "issuse".
