### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by aikar** [Nukkit/Nukkit#1369]
Hello,
I was unaware of another project including my Timings v2! I'm glad you did.

Although I'm requesting you please include my copyright headers and remove @author tags

Please see my original versions for reference: https://github.com/aikar/Bukkit/tree/master/src/main/java/co/aikar/timings

I've also added Nukkit to the allowed list, so please update https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/timings/TimingsExport.java#L183

to Nukkit/ prefix

And if possible, for the main timings API classes (ie: not the ones like Level Timings that are containers for handlers),
 if you can please relocate the package back to its original location co.aikar.timings so we can keep things consistent with implementations (as well as if you run into any code looking for my timings system, it will break here as it's not in the correct package)

For API compat, you could keep a cn/nukkit/timings/Timing(s) class that forwards to the co.aikar.timings one, but i'm not sure if you even have plugins using Timings as an API.

One day we might see Timings API/Core as an external library to include, which would be nice so that I can manage the implementation in 1 place and everyone can just bump a version number.

Thanks!

**Comment by Tee7even** [comment]
I guess you won't mind if we won't relocate anything from cn.nukkit.timings to original location? Since Nukkit is in kind of almost abandoned state (the best comparison would be that it's **on life support** - updated as much as needed to enter with new versions and maybe _some_ features added), I don't clearly remember everything (anything) about this implementation of Timings v2 and I'm not sure if this moving won't ruin something. As for everything else - yes, as soon as possible.

**Comment by aikar** [comment]
yeah i don't "need" you to do it, just would be better if it was there.
