### ISSUE TITLE
 Feb 03, 2017 12:43:32 PM io.netty.channel.DefaultChannelId defaultMachineId

### ISSUE THREAD

**Issue by KingTux2** [Nukkit/Nukkit#1460]
12:43:32 [INFO] Done (0.776s)! For help, type "help" or "?"
> Feb 03, 2017 12:43:32 PM io.netty.channel.DefaultChannelId defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 10:da:de:e8:3c:3c:8c:aa

**Comment by MrPowerGamerBR** [comment]
Just ignore the error, it says that but Nukkit works, so...

**Comment by MrPowerGamerBR** [comment]
This happens because Nukkit's Netty library is outdated, updating the library should fix the issue.

**Comment by Pub4Game** [comment]
Just return everything as it was... All these changes only made it worse.

**Comment by MrPowerGamerBR** [comment]
@Pub4Game this isn't related to JLine, this is related to Netty, and no commit did mess around with Netty at all.

And this doesn't happen in every machine, my dedicated server doesn't have this issue, but my VPS has this issue. Again, it doesn't affect Nukkit in any way because I still could connect to the server just fine.

StackOverflow: http://stackoverflow.com/questions/32302515/failed-to-find-a-usable-hardware-address-from-the-network-interfaces

Strangely Nukkit already has an up to date Netty but still has this issue... But again, Netty issue, but doesn't affect Nukkit in any way whatsoever.

**Comment by MrPowerGamerBR** [comment]
And again, if you still want to revert, I already said how to, just press "Revert" in the pull request and merge to the master branch.

Or you can just ```git clone https://github.com/Nukkit/Nukkit.git```, ```git reset --hard commit```, ```git force --push``` (this will probably break some things so don't do that unless if you are 100% sure that it won't break anything)

**Comment by KingTux2** [comment]
Ok, thank you.

**Comment by JackboyPlay** [comment]
Its not only on nukkit its on spigot and I think pocketmine too

**Comment by MrPowerGamerBR** [comment]
@JackboyPlay PocketMine-MP doesn't have this message because it doesn't use Netty, but Spigot may have this message because it also uses Netty
