### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by CraftYourBukkit** [Nukkit/Nukkit#1726]
Sometimes when I join the server I don't have access to commands. Can you help me?

**Comment by JackboyPlay** [comment]
What do you mean with "no acess"?

**Comment by Snake1999** [comment]
This is because packet loss caused by bad internet. Your service provided by the ISP might have lost the packet of command list, which is several kilobytes by size.
What I can advise you are:
1. Try proper ways of user interface. I mean you don't have to use commands everywhere, especially when player have to recite all usages of commands, think out other ways such as, NPC, clicking blocks or signs or so.
2. Make a way of resending packet. Ask google or your technician about packet resending.

btw, NEXT TIME USE PROPER TEMPERLATE AND DETAILED TITLE
