### ISSUE TITLE
ingame lags

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#194]
MCPE is laggy so chunk loading issue

**Comment by Pub4Game** [comment]
yes...

**Comment by MagicDroidX** [comment]
I think it is because MCPE is recalculating lights.

**Comment by Pub4Game** [comment]
Why single player does not lag then?

**Comment by MagicDroidX** [comment]
In sp game, lights are calculated when each chunk being generated.
In mp vame, Nukkit won't calculate lights and client have too many chunks to calculate.

**Comment by Pub4Game** [comment]
And there's no way to fix it?( So the lag will remain?

**Comment by MagicDroidX** [comment]
No, the only way to fix is to make Nukkit calculate lights. It might be buggy.

**Comment by Pub4Game** [comment]
Try to make... Because this lag really spoil the overall feel of Nukkit

**Comment by Creeperface01** [comment]
But this lag is not in pocketmine

**Comment by PEMapModder** [comment]
What about sending the chunks more slowly?

**Comment by Creeperface01** [comment]
Yes thaths right when player move into blocks it damage him each tick xD too

**Comment by MagicDroidX** [comment]
Alright we have already found the reason for the lags. It is the unlimited updating of liquids. Maybe a bug caused by the generator. We are now thinking how to fix it. I am sorry for the bad experience.

**Comment by Creeperface01** [comment]
Its Awesome!

**Comment by Angelic47** [comment]
So the lag is caused by grass blocks which have liquid on it. Nukkit will update grass blocks randomly, if you put liquid on it, it would become to dirt block soon. So the problem is here, too many grass blocks generated under the water, so there are thousands of update which clients can't keep up.
PM doesn't have this problem because it won't check the grass blocks at all, and grass blocks would never become to dirt blocks in pm.
We are now thinking how to fix it.

**Comment by Creeperface01** [comment]
So change the generator

**Comment by Creeperface01** [comment]
And prevent generating grass under water

**Comment by Angelic47** [comment]
Yeah, in my opinion, generator needs to change a lot. There are too many features that we are not implemented yet.
