### ISSUE TITLE
NBTIO NPE

### ISSUE THREAD

**Issue by JackboyPlay** [Nukkit/Nukkit#1989]
### Actual Behavior

If I try to do NBTIO.write(myCompoundTag) it will throw a NPE.

### Steps to Reproduce

Execute NBTIO.write(yourCompoundTag);

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

Error: https://pastebin.com/yhNFWv6Z
Debugpaste: https://pastebin.com/KMW2dqje
My code: https://pastebin.com/04R1hhJL

**Checklist**:

- [x] I included a `/debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of Nukkit
- [x] I Made sure the bug/error is not caused by a plugin

**Comment by sero583** [comment]
Close issue, don't forget in 90% of plugin errors it's <b>your</b> fault, not the software's and NBTIO.write(args); works very fine. You should find your mistake yourself, as long as you dont share more code. Good luck and here is a hint (!!!)
``de.jackboyplay.toxcraft.kernplugin.mechaniken.LanguageManager.translateSigns(LanguageManager.java:191)
        at de.jackboyplay.toxcraft.kernplugin.mechaniken.LanguageManager.addSign(LanguageManager.java:206)
        at de.jackboyplay.toxcraft.kernplugin.events.PlayerInteract.onInteract(PlayerInteract.java:24)
``
Means check your lang manager and these lines out. Make sure they are working fine, probably something returns null from your methods I also can't say why because I have no code.
