### ISSUE TITLE
blocking issue

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#274]
it say blocked IP Adress for 5 seconds

but then this ip is blocked until restart :D

**Comment by xpyctum** [comment]
Yes, confirm issue!

**Comment by ProjectInfinity** [comment]
What are you doing to cause the IP to be blocked?

**Comment by Creeperface01** [comment]
I had 19 hunger and i eat a melon xD

**Comment by Snake1999** [comment]
Okay, I'd say it again that, blocking address is NOT the cause of problem but a PROTECT system that if anything strange with someone, for example trying to hack, that systen prevent this server from crashing or being hacked. 

But here, eating food is not available yet. Food is in our to-do list. If someone tries to eat food, nukkit with food feature undone will think it's "hack"... So what we Nukkit Team should to is to finish food system', rather than talk about how blocking address happens :D

**Comment by Creeperface01** [comment]
Yes i know but why it says blocked for 5 seconds if im blocked forever xD

**Comment by Snake1999** [comment]
For client side, 5 seconds is enough as timeout :/

**Comment by ProjectInfinity** [comment]
You're not getting it. It should have removed the block after 5 seconds, but it never does.

**Comment by MagicDroidX** [comment]
Fixed
