### ISSUE TITLE
Survival update

### ISSUE THREAD

**Issue by xpyctum** [Nukkit/Nukkit#385]
- [x] Get "In Progress" :D 
- [x] Working chests
- [x] Working furnace

**Comment by markkrueg** [comment]
Awesome! Looking forward to this.

**Comment by shanwer** [comment]
Yes,these are very important bugs.

**Comment by Pub4Game** [comment]
@shanwer This is not a bug =_= It's just not implemented

**Comment by xpyctum** [comment]
@shanwer ...

**Comment by xpyctum** [comment]
Why? :<

**Comment by MagicDroidX** [comment]
It works now!

**Comment by xpyctum** [comment]
@MagicDroidX Commit?

**Comment by MagicDroidX** [comment]
@xpyctum In @Creeperface01 's pull requests.

**Comment by Pub4Game** [comment]
:+1:

**Comment by xpyctum** [comment]
@MagicDroidX #408 ?

**Comment by MagicDroidX** [comment]
@xpyctum That's right.

**Comment by Creeperface01** [comment]
but double chest still don't work

**Comment by MrPowerGamerBR** [comment]
Chests and Furnaces works? Fancy! Now only just one more step (actually two, if you count mob AI) so Nukkit can be used to Survival Servers :+1: Good job!

**Comment by xpyctum** [comment]
@MrPowerGamerBR Double chests not works.

**Comment by MrPowerGamerBR** [comment]
@xpyctum that's the "one more step" I said, the only missing feature is double chests.

**Comment by MrPowerGamerBR** [comment]
@xpyctum after testing the new build with the chests, the double chest issue isn't really a "HUGE" issue, when you said that double chest doesn't work yet, I thought I could only interact with the first chest slots (and the second chest slots was uninteractable/unaccessible), but in reality the two chests are separate instead of merged.
