### ISSUE TITLE
[Feature] API Update, but which way? Share your idea!

### ISSUE THREAD

**Issue by Snake1999** [Nukkit/Nukkit#466]
We renamed internal structures these days, everyone are talking about it. I first think why we discussed it, and finally I know is the problem about Nukkit API. We sometimes compare with bukkit:
Minecraft Kernel + Bukkit API = CraftBukkit
Nukkit Kernel + Nukkit API = Nukkit
And I see, the lack of API, can confuse developers, and add many inconveniences. We think it must be added that Nukkit should have a set of API, or Nukkit won't be Nukkit.

We should add APIs. How to add API is easy, but figuring out **which way** need everyone to discuss. We can start from: Put into which package? Have a structure like what? 

You are not just talking. You are designing the API structure, you are designing the future of Nukkit, and the way you works on it. Have fun sharing idea, and we will make all API available **just the way you like and need to**.

Welcome to share your idea! :D

**Comment by Snake1999** [comment]
ok I've got it, add both bukkit and pocketmine api adapt. Add package cn.nukkit.material. :D

**Comment by Pub4Game** [comment]
:smile:

**Comment by PeratX** [comment]
@Snake1999 So cold here...

**Comment by fromgate** [comment]
I would like to suggest an additional configuration class: https://github.com/Nukkit/Nukkit/pull/486
This class is not breaking original Config, but just adds ability to work with config files easier.
So old plugins will work too and plugin developers could chose the how to work with config.

I got the idea for SimpleConfig from popular bukkit plugin  [Yamler](https://www.spigotmc.org/resources/yamler.315/) (It was recreated for Nukkit too - [Yamler for Nukkit](http://nukkit.ru/resources/yamler.37/).
But I think this idea is really good and must be part of Nukkit, instead of external plugin (or library).

It's a minor API addition, but I think it would be really useful.

**Comment by SkygridRex** [comment]
in my opinion I agree that the Nukkit API should be restructured similarly Bukkit server software to facilitate the porting of Bukkit plugins to Nukkit, it would be a matter of just rename file paths. Think about it

**Comment by MrPowerGamerBR** [comment]
@SkygridRex but now porting PocketMine plugins to Nukkit is easier because the Nukkit API is almost the same API from PocketMine.

**Comment by SkygridRex** [comment]
@MrPowerGamerBR  But... Bukkit hace better plugins

**Comment by swift2plunder** [comment]
Forgive the obvious, but Bukkit and Nukkit are both Java. If everything else was equal (and it's not) then it'll be easier to cross develop Bukkit and Nukkit plugins than PocketMine and Nukkit. There is the existing investment in laying the groundwork for a Pocketmine-like API and the existing plugins, but this is probably the best opportunity we'll have to make this kind of change.

**Comment by SkygridRex** [comment]
I don't understand at all because i don't speak english @swift2plunder can you say that more simple?

**Comment by swift2plunder** [comment]
Bukkit is written in Java. I think it would be better to use the API from another Java program than from a PHP program because it would be easier to use the same code. 

It's not an easy change, but I think it would be worth it. If you do make that change, the sooner you do it the easier it will be.

**Comment by MrPowerGamerBR** [comment]
@swift2plunder yeah, while I would love the Bukkit API instead of the PocketMine-MP API, I don't think they would change the API now.

I was creating a BukkitAPI implementation to Nukkit: https://github.com/MrPowerGamerBR/CharaDreamer

However I never finished it because I'm lazy and I was having some issues, but it does work. (well, you can use Bukkit.broadcastMessage("Howdy"); and Bukkit.getWorld("world").getPlayers(), so that's something, I guess.)

**Comment by SkygridRex** [comment]
It's better change the API now to avoid problems for developers

**Comment by Tee7even** [comment]
Excuse me for bumping old threads, but yeah, it would be nicer to follow Bukkit's example than PocketMine's. Not just because it would be easier to port Bukkit plugins this way (that too!), but also because, since Bukkit was natively written in Java (not a port from any other language), it is better optimised. Copying from PHP has it's downsides and the main one is that the same thing could be done in Java better.

**Comment by Pub4Game** [comment]
@Tee7even Thoughts of a man who knows nothing about Bukkit...

It is very difficult, because you can't pull a piece of code there and paste here...

**Comment by Tee7even** [comment]
>Thoughts of a man who knows nothing about Bukkit...

Oh, you want to argue about it?
![I too like to live dangerously](http://i.imgur.com/PNBF707.jpg)

>It is very difficult, because you can't pull a piece of code there and paste here...

Who, the heck, said about copying? Noone, but you.

**Comment by Pub4Game** [comment]
Stop. Do you suggest to implement the Bukkit API without code? You're a goddamn genius! Do the two APIs! Only a complete fool would begin to pull off... a man who is unable himself to write something great and needed, but likes to sit all over ready

**Comment by Pub4Game** [comment]
> Who, the heck, said about copying? Noone, but you.

I thought you were talking about copying the code, I'm sorry I got you wrong.

Has already begun changing the structure, for example, @fromgate in the future plans to implement `Material`

**Comment by swift2plunder** [comment]
I'm the one who brought up code reuse, but I never meant to imply cut and paste interoperability with Bukkit would be possible. Program A and Program B are different. Right now we have programming language A with API B. That means zero code reuse whether we're porting a plugin from A or B. 

Nukkit isn't Bukkit, but if they shared an API as well as a programming language there would be code reuse > 0. I'm not in a position to say whether that code reuse is worth refactoring the code at this point. I just wanted to point out the potential so those with the experience would take it into consideration.

**Comment by Tee7even** [comment]
>Stop. Do you suggest to implement the Bukkit API without code? You're a goddamn genius! Do the two APIs! Only a complete fool would begin to pull off... a man who is unable himself to write something great and needed, but likes to sit all over ready

Once again, I haven't said neither about implementing the Bukkit API in Nukkit, nor "pulling off". Well, now I see your last message, maybe you need a dictionary? Or let _me_ help you with this: **"to follow example"** (брать пример/следовать примеру) doesn't necesary mean "to do exactly the same".
I said about **looking at bukkit** and **adopting some good practice**, restructuring Nukkit API before releasing "1.0", because later it would get too difficult, if devs want to keep their code quality and stable. Unlike you said, I know  _at least something_ about Bukkit. PM resembles it to a certain degree and the whole situation now reminds me of machine translation. You know, that case when you translate some statements to another language and then back and it gets corrupted.

**Comment by Pub4Game** [comment]
If you didn't see, I just wrote THIS EXAMPLE! This is well implemented in Bukkit, so why would it not be used in Nukkit?

We want to do the same, not because we want Bukkit, but because there it is implemented thoughtfully and correctly.

**Comment by Tee7even** [comment]
@swift2plunder I guess, I'm of the same opinion, didn't get those "A and B" examples though.
@Pub4Game Nice. I guess noone here meant implementing Bukkit in Nukkit and it's good that we understand each other now.

**Comment by SkygridRex** [comment]
PM is really outdated! It's time to take your own way

**Comment by KairusDarkSeeker** [comment]
android app

**Comment by Pub4Game** [comment]
@KairusDarkSeeker Not feasible

**Comment by Tee7even** [comment]
@Pub4Game Somehow modders were able to make android launcher for PC Minecraft. Just saying. I don't think it would be cool to use that technique for Nukkit, if possible at all.

**Comment by EnderKenji** [comment]
Make a Proxy server for it? So it can easily teleport to other server?

**Comment by iNevet** [comment]
@EnderKenji See https://github.com/Nukkit/WarpEngine

**Comment by EnderKenji** [comment]
@iNevet Thanks. Another suggestion is some DevTools commands. Like load plugin by source,
/makeplugin, /extractplugin etc

**Comment by Tee7even** [comment]
@EnderKenji It is implemented by plugins, no need for this in main server code.

**Comment by KairusDarkSeeker** [comment]
@Pub4Game its possible because Nukkit is java and java is compatible with android

**Comment by Tee7even** [comment]
@KairusDarkSeeker another one... Here, look:
1)Android uses its own implementation of Java.
2)No Java 8 for Android. But it's secondary problem.

**Comment by KairusDarkSeeker** [comment]
@Tee7even :/

**Comment by fromgate** [comment]
Using Enums in Nukkit
===============

I think there too much code in Nukkit that was directly translated from PM without using Java's alternatives.

First, I wanna talk about using enums.
TextFormat, packet types, colors, event types, item and block types, directions, etc. could be implemented as enums.

**Why enums?**
1. Enums has fixed amount of values and you cannot modify it without recompile. For example if you use final static for direction:
```
public static final int UP = 0;
public static final int DOWN = 1;
```
And method
```
public void moveUpOrDown (Player player, int direction){
    ////
}
```
You will be able to call this method with unsupported parameter:
```
moveUpOrDown (fromgate, 100500);
```

But if you use enums - it's not possible:
```
public enum Direction {
   UP,
   DOWN;
}
////////////

public void moveUpOrDown (Player player, Direction direction){
    ////
}

////////////
moveUpOrDown (fromgate, Direction.UP);
```

2. Enums can contain variables and objects. So you can define one or more specific constants related to selected enum values.
For example, item types could be defined like:
```
public enum Material{
	STONE (0, 0, Stone.class),
	STONE_GRANITE (0, 1, Stone.class),
	STONE_GRANITE_POLISHED (0, 2, Stone.class),
	STONE_DIORITE (0, 3, Stone.class),
	STONE_DIORITE_POLISHED (0, 4, Stone.class),
	STONE_ANDESITE (0, 5, Stone.class),
	STONE_ANDESTIE_POLISHED (0, 6, Stone.class);
}
```

I know that @Pub4Game already started to recreate TextFormat https://github.com/Pub4Game/Nukkit/commit/de99e575f3b69d366ad1b004c73f21a412b38369

And I think this new TextFormat must be added to Nukkit. 

And we must start to modify other lists of constants that currently implemented as "static final"...

**Comment by TheDiamondYT1** [comment]
Why not just fork Bukkit and edit it for your needs? [That's what the glowstone team did](https://github.com/GlowstoneMC/Glowkit-Legacy).

**Comment by KairusDarkSeeker** [comment]
@TheDiamondYT1 nigga y don't u do it? actually its impossible

**Comment by TheDiamondYT1** [comment]
ITS not that hard
