### ISSUE TITLE
Cancelling PlayerInteractEvent for door ignored when player clicking the top side of the door.

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#495]
How to reproduce:
1. Code:
```
    @EventHandler (ignoreCancelled =  true, priority = EventPriority.NORMAL)
    public void onInteractDoor (PlayerInteractEvent event) {
        switch (event.getBlock().getId()){
            case Block.DOOR_BLOCK:
            case Block.ACACIA_DOOR_BLOCK:
            case Block.DARK_OAK_DOOR_BLOCK:
            case Block.BIRCH_DOOR_BLOCK:
            case Block.JUNGLE_DOOR_BLOCK:
            case Block.SPRUCE_DOOR_BLOCK:
                event.setCancelled();
        }
    }
```

2. Place a door on server and try to open it.
3. When you click bottom part of the door - it closes (because event was cancelled).
4. When you click top block of the door - door will be opened... :(

**Comment by Snake1999** [comment]
If OK, try listen DoorToggleEvent instead))

**Comment by fromgate** [comment]
Oh! Thanks! I will try it :)

**Comment by fromgate** [comment]
@Snake1999 same effect with DoorToggleEvent - click bottom block don't opens door, but clicking top side - opens. Event is canceled...

**Comment by Snake1999** [comment]
Confirmed. Such a strange bug :3

**Comment by Snake1999** [comment]
I checked out server side, the meta behaves correctly, and packets are sent correctly(sent nothing because door open is cancelled), but mojang client seems unlikely to accept these, the client behaves like door opens as its prediction, but quit+rejoin server you can see it is cancelled :/ Same bug as flower pots does not updates correctly
For why only upper side cause this, the door is open or closed due to the downside block.

**Comment by fromgate** [comment]
Ok! I hope in 0.14.0 it will be fixed.
