### ISSUE TITLE
Why he thinks that the picture of this player?

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#498]
![image](https://cloud.githubusercontent.com/assets/11244874/13026816/cf36b5d0-d246-11e5-8bb5-8d7bf8f1b953.png)

![image](https://cloud.githubusercontent.com/assets/11244874/13026827/025b83aa-d247-11e5-97a3-3dcce6efaf00.png)

**Comment by MagicDroidX** [comment]
You are getting a damager...

**Comment by MrPowerGamerBR** [comment]
What? Do you think that a painting can't be a player? You should allow other painting wishes, if a painting wants to be a player, let it be a player.

(just kidding)

@MagicDroidX is right, also, this will happen with every entity, because you are verifying if the damager is player and not verifying the victim.

**Comment by MagicDroidX** [comment]
@MrPowerGamerBR XD

**Comment by Pub4Game** [comment]
@MrPowerGamerBR xD

**Comment by Pub4Game** [comment]
Hmm... I did not get(

**Comment by Pub4Game** [comment]
@MagicDroidX Thank you :3
