### ISSUE TITLE
Food stop decreasing after eating

### ISSUE THREAD

**Issue by Guillaume351** [Nukkit/Nukkit#530]
If I connect, I run a bit, I start to loose hunger. Then I eat a steak. I can run as much as I want (3 - 4 minutes of sprint), the hunger will not decrease.
Debug messages not showing after eating, so I guess saturation is not decreasing too

> 2016-2-23 12:13:43 [DEBUG] Guillaume351 set foodLevel: foodLevel = 20  saturationLevel = 0.0
2016-2-23 12:13:51 [DEBUG] Guillaume351 set foodLevel: foodLevel = 19  saturationLevel = 0.0
2016-2-23 12:13:56 [DEBUG] Guillaume351 set foodLevel: foodLevel = 18  saturationLevel = 0.0
2016-2-23 12:14:00 [DEBUG] Guillaume351 set foodLevel: foodLevel = 17  saturationLevel = 0.0
2016-2-23 12:14:10 [DEBUG] Guillaume351 set foodLevel: foodLevel = 20  saturationLevel = 12.8 < Eating a steak

**Comment by Snake1999** [comment]
You can check wiki and found:

1. you have 20 food level and 20 saturation level. Only food level is visible. 
2. if you run, jump, or do other things, saturation level will decrease first. 
3. Only after saturation level become 0 when food level start to decrease. 
4. Only if food level decreases, you will found your hunger decreasing. 

That's why food level seems stable at first but decrease so fast after some moments.
:)

**Comment by Guillaume351** [comment]
Yep I know, but saturation doesn't seems to decrease after :/ I can play for a long time I will never need to eat again.
