### ISSUE TITLE
MCPE crashes

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit/Nukkit#707]
if there are more players, mcpe crashes.... i hope you fix this issue soon

**Comment by Snake1999** [comment]
What?

**Comment by Guillaume351** [comment]
I have the same issue (I think) : when there are a lot of player, I often get null pointer exeption when on a get player, I will try to copy/paste the error when I get it

**Comment by Creeperface01** [comment]
no, if you play on android so MCPE crashes if you send AddPlayerPacket.. but idk why.. maybe UUID? Item? because it happens only in lobby (on my server) and there are NPCs (fake players). And players spawn with items with custom name

**Comment by boybook** [comment]
Maybe I found the reason.
![screenshot_2016-04-24-13-16-08_com miui bugreport_1461599087745](https://cloud.githubusercontent.com/assets/8210983/14789565/c3da9e94-0ad2-11e6-8096-3e526304bd75.jpg)
The crash log shows: carshed because of the Item In Hand.
So when players teleported, I keep the air in players' hand. Then the game not crashed.
Maybe it is a client side bug, or a bug in Nukkit.

**Comment by Creeperface01** [comment]
But why all players have same item in hand but it doesnt crash everytime when someone join

**Comment by Creeperface01** [comment]
Btw how to make crash log?

**Comment by Snake1999** [comment]
Can't reproduce as no further logs provided.
