### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by mfmfneko** [Nukkit/Nukkit#74]
When I start the server to crash.

Log:
```
[INFO] Welcome! Please choose a language first!
[ALERT] java.lang.NullPointerException
	at java.io.Reader.<init>(Unknown Source)
	at java.io.InputStreamReader.<init>(Unknown Source)
	at cn.nukkit.utils.Utils.readFile(Utils.java:57)
	at cn.nukkit.Server.<init>(Server.java:195)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**Comment by Angelic47** [comment]
It seems that some files about language in src/resouces/lang was missing.
Now language files are using submodule, and you can't get it by running "git clone" or download zip.

Now it can be fixed by following steps:
1.use command "git submodules init"
2.use command "git submodules update"
3.compile it and enjoy

You also can fix it by download Nukkit_Multi Language and extract it to src/resources/lang, which you can find it at https://github.com/Nukkit/Multi-language.

Good luck!

**Comment by mfmfneko** [comment]
@Angelic47 Sorry, I did should see more README.
I will make sure that this will never happen again.
Thank you for your reply.

**Comment by Angelic47** [comment]
@mfmfneko No problem. We are happy to help :D
Please let us know if you have any problem
