### ISSUE TITLE
The world is not loaded

### ISSUE THREAD

**Issue by Pub4Game** [Nukkit/Nukkit#75]
![image](https://cloud.githubusercontent.com/assets/11244874/11442150/f870de2c-9523-11e5-92c9-45d76e8246f0.png)
![image](https://cloud.githubusercontent.com/assets/11244874/11442151/fbcb7c58-9523-11e5-83ad-65a9f62e23de.png)

**Comment by Angelic47** [comment]
Nukkit is not finished, so there is no world generator yet.
But don't worry, now you can use flat world generator, just set "level-type=FLAT" in server.properties. It means that you can create a flat world now.
And, ANVIL is now support, which allow you import saves to nukkit. Finally, we will add world generator soon :D

**Comment by Angelic47** [comment]
Nukkit is not finished, so there is no world generator yet.
But don't worry, now you can use flat world generator, just set "level-type=FLAT" in server.properties. It means that you can create a flat world now.
And, ANVIL is now support, which allow you import saves to nukkit. Finally, we will add world generator soon :D
Tip: Remember to delete "world" directory and "player" directory after changed server.properties in order to generating a new world.

**Comment by Pub4Game** [comment]
Sure! Sorry, I forgot about the "level-type=FLAT"

**Comment by Pub4Game** [comment]
Thanks!

**Comment by Angelic47** [comment]
@Pub4Game No problem, we are happly to help :D
Have fun with nukkit!
